#ifndef FLORA_CONSTANTS_H
#define FLORA_CONSTANTS_H

#define FLORA_ENGINE_FATAL 1
#define FLORA_ENGINE_SUCCESS 0
#define INITIAL_EVENT_QUEUE_CAPACITY 8
#define INITIAL_WIDGET_CAPACITY 8
#define GROWTH_FACTOR 2

#endif // !FLORA_CONSTANTS_H
