#ifndef FLORA_CONSTANTS_H
#define FLORA_CONSTANTS_H

#define FLORA_WIDOW_WIDTH 800
#define FLORA_WIDOW_HEIGHT 600

#define FPS 60
#define FRAME_TARGET_TIME (1000 / FPS)

#define MAX_FLORA_WIDGETS 8


#endif // !FLORA_CONSTANTS_H

